import { calculatePerformance } from "@/lib/domain/metrics";
import type { PerformanceRow } from "@/lib/domain/types";

const rawPerformance: PerformanceRow[] = [
  {
    id: "campaign-content-tung",
    name: "ucmas / mess / content a tùng",
    owner: "haitran",
    brand: "ucmas",
    objective: "Tin nhắn",
    status: "active",
    spend: 12_400_000,
    messages: 318,
    sql: 112,
    rank1: 61,
    rank2: 41,
    rank3: 18,
    rank4: 5,
    duplicateRate: 0.032,
    invalidRate: 0.002,
    matchRate: 0.156,
    cpm: 51_200,
    ctr: 0.013,
    frequency: 2.4,
    zone: "scale",
    trend: -0.042,
  },
  {
    id: "campaign-tuyen-sinh-he",
    name: "ucmas / mess / tuyển sinh hè",
    owner: "haicm",
    brand: "ucmas",
    objective: "Tin nhắn",
    status: "active",
    spend: 8_100_000,
    messages: 240,
    sql: 96,
    rank1: 17,
    rank2: 12,
    rank3: 3,
    rank4: 0,
    duplicateRate: 0.071,
    invalidRate: 0.004,
    matchRate: 0.104,
    cpm: 47_800,
    ctr: 0.017,
    frequency: 2.8,
    zone: "trap",
    warning: "Bẫy số rẻ",
    trend: 0.08,
  },
  {
    id: "campaign-ren-nao",
    name: "ucmas / mess / rèn não bộ",
    owner: "haitran",
    brand: "ucmas",
    objective: "Tin nhắn",
    status: "active",
    spend: 9_600_000,
    messages: 268,
    sql: 98,
    rank1: 49,
    rank2: 33,
    rank3: 11,
    rank4: 3,
    duplicateRate: 0.028,
    invalidRate: 0.001,
    matchRate: 0.162,
    cpm: 49_100,
    ctr: 0.015,
    frequency: 2.2,
    zone: "scale",
    trend: -0.07,
  },
  {
    id: "campaign-qua-tang-he",
    name: "ucmas / mess / quà tặng hè",
    owner: "linhpt",
    brand: "ucmas",
    objective: "Tin nhắn",
    status: "active",
    spend: 6_800_000,
    messages: 165,
    sql: 40,
    rank1: 25,
    rank2: 16,
    rank3: 5,
    rank4: 1,
    duplicateRate: 0.055,
    invalidRate: 0.003,
    matchRate: 0.131,
    cpm: 56_400,
    ctr: 0.011,
    frequency: 3.4,
    zone: "expensive",
    warning: "CPR leo thang",
    trend: 0.46,
  },
  {
    id: "campaign-tu-duy-toan",
    name: "uckid / mess / tư duy toán",
    owner: "linhpt",
    brand: "uckid",
    objective: "Tin nhắn",
    status: "active",
    spend: 5_200_000,
    messages: 124,
    sql: 15,
    rank1: 3,
    rank2: 2,
    rank3: 0,
    rank4: 0,
    duplicateRate: 0.083,
    invalidRate: 0.008,
    matchRate: 0.088,
    cpm: 60_100,
    ctr: 0.009,
    frequency: 3.8,
    zone: "stop",
    warning: "Đốt tiền không ra số",
    trend: 0.32,
  },
  {
    id: "campaign-be-5-tuoi",
    name: "uckid / mess / bé 5 tuổi",
    owner: "haicm",
    brand: "uckid",
    objective: "Tin nhắn",
    status: "active",
    spend: 1_200_000,
    messages: 16,
    sql: 3,
    rank1: 1,
    rank2: 0,
    rank3: 0,
    rank4: 0,
    duplicateRate: 0,
    invalidRate: 0,
    matchRate: 0,
    cpm: 52_600,
    ctr: 0.012,
    frequency: 1.2,
    zone: "unranked",
  },
  {
    id: "campaign-khai-giang",
    name: "uckid / mess / khai giảng tháng 6",
    owner: "ngocanh",
    brand: "uckid",
    objective: "Tin nhắn",
    status: "paused",
    spend: 2_900_000,
    messages: 81,
    sql: 19,
    rank1: 10,
    rank2: 5,
    rank3: 1,
    rank4: 0,
    duplicateRate: 0.026,
    invalidRate: 0.002,
    matchRate: 0.119,
    cpm: 45_900,
    ctr: 0.014,
    frequency: 2.1,
    zone: "expensive",
    trend: -0.02,
  },
  {
    id: "campaign-trai-he",
    name: "ucmas / mess / trại hè trí tuệ",
    owner: "ngocanh",
    brand: "ucmas",
    objective: "Tin nhắn",
    status: "paused",
    spend: 2_000_000,
    messages: 28,
    sql: 29,
    rank1: 16,
    rank2: 8,
    rank3: 2,
    rank4: 0,
    duplicateRate: 0.041,
    invalidRate: 0.002,
    matchRate: 0.143,
    cpm: 58_700,
    ctr: 0.01,
    frequency: 1.8,
    zone: "trap",
    warning: "Tỷ lệ lấy số vượt 100%",
    trend: 0.12,
  },
];

export const performanceRows = rawPerformance.map((row) => calculatePerformance(row));

export const kpis = [
  { key: "spend", label: "Chi tiêu", value: 48_200_000, delta: 0.123, quality: "neutral", kind: "money" },
  { key: "messages", label: "Tin nhắn", value: 1_240, delta: 0.081, quality: "good", kind: "count" },
  { key: "cpr", label: "CPR", value: 38_871, delta: 0.039, quality: "bad", kind: "money" },
  { key: "sql", label: "SQL", value: 412, delta: -0.021, quality: "bad", kind: "count" },
  { key: "capture", label: "Tỷ lệ lấy số", value: 0.332, delta: -0.064, quality: "bad", kind: "percent" },
  { key: "cpsql", label: "CPSQL", value: 116_990, delta: 0.148, quality: "bad", kind: "money" },
] as const;

export const funnelSteps = [
  { label: "Tin nhắn", value: 1_240, rate: 1, owner: "Meta / người chạy ads" },
  { label: "SĐT (SQL)", value: 412, rate: 0.332, owner: "Đội chat" },
  { label: "Bậc 1+", value: 198, rate: 0.481, owner: "Đội tư vấn" },
  { label: "Bậc 2+", value: 87, rate: 0.439, owner: "Đội tư vấn" },
  { label: "Bậc 3+", value: 31, rate: 0.356, owner: "Đội tư vấn" },
  { label: "Bậc 4", value: 9, rate: 0.29, owner: "Đội tư vấn", immature: true },
];

export const trendData = Array.from({ length: 30 }, (_, index) => {
  const spend = Math.round(900_000 + Math.abs(Math.sin(index * 0.55 + 0.6)) * 1_100_000 + (index % 7 < 5 ? 350_000 : 0));
  const sql = Math.round(7 + Math.abs(Math.sin(index * 0.41 + 1.4)) * 16);
  return {
    day: `${String(index + 1).padStart(2, "0")}/06`,
    spend,
    sql,
    cpsql: Math.round(spend / Math.max(sql, 1)),
  };
});

export const ownerCapture = [
  { name: "haitran", value: 0.381 },
  { name: "haicm", value: 0.354 },
  { name: "linhpt", value: 0.297 },
  { name: "ngocanh", value: 0.224 },
];

export const brandLevels = [
  { brand: "UCMAS", rank0: 52, rank1: 28, rank2: 13, rank3: 5, rank4: 2 },
  { brand: "UCKID", rank0: 66, rank1: 21, rank2: 8, rank3: 4, rank4: 1 },
];

export const dataHealth = [
  { label: "Lead có gắn quảng cáo", value: 0.784, previous: 0.791, tone: "blue" },
  { label: "Lead khớp được CRM", value: 0.126, previous: 0.122, tone: "amber", info: true },
  { label: "SĐT lỗi định dạng", value: 0.003, previous: 0.004, tone: "green" },
  { label: "SĐT trùng", value: 0.041, previous: 0.037, tone: "green" },
];

export const alerts = [
  {
    id: "a1",
    severity: "high",
    label: "Bẫy số rẻ",
    object: "ucmas / mess / tuyển sinh hè · Rèn não bộ - Mở tư duy",
    overspend: 2_400_000,
    evidence: [
      { label: "CPSQL", value: "84 N", reference: "trung vị 117 N — rẻ hơn 28%", quality: "good" },
      { label: "Tỷ lệ thoát bậc 0", value: "18,2%", reference: "trung vị 48,1% — chỉ bằng 38%", quality: "bad" },
    ],
    action: "Không tăng ngân sách. Quảng cáo ra số rẻ nhưng gần như không có số nào đi tiếp. Soi lại creative và độ tuổi tệp.",
  },
  {
    id: "a2",
    severity: "high",
    label: "Đốt tiền không ra số",
    object: "uckid / mess / tư duy toán",
    overspend: 1_800_000,
    evidence: [
      { label: "CPSQL", value: "341 N", reference: "trung vị 117 N — đắt gấp 2,9 lần", quality: "bad" },
      { label: "Tỷ lệ lấy số", value: "24,7%", reference: "trung vị 33,2%", quality: "bad" },
    ],
    action: "Tắt quảng cáo, dồn ngân sách sang nhóm Nhân rộng. Cả CPSQL lẫn chất lượng đều tệ.",
  },
  {
    id: "a3",
    severity: "medium",
    label: "CPR leo thang",
    object: "ucmas / mess / quà tặng hè",
    overspend: 680_000,
    evidence: [
      { label: "CPR", value: "41,2 N", reference: "trung vị 38,9 N — cao hơn 6%", quality: "bad" },
      { label: "Frequency", value: "3,4", reference: "ngưỡng 3,0", quality: "bad" },
    ],
    action: "Tệp bắt đầu bão hòa. Làm mới creative hoặc mở rộng tệp trong 3–5 ngày tới.",
  },
  {
    id: "a4",
    severity: "low",
    label: "Tỷ trọng organic tăng",
    object: "Toàn tài khoản uckid",
    overspend: 0,
    evidence: [
      { label: "Organic", value: "21,6%", reference: "kỳ trước 18,1%", quality: "neutral" },
    ],
    action: "Theo dõi. Tỷ trọng organic tăng có thể làm nhiễu phân bổ số cho quảng cáo.",
  },
] as const;

export const leads = [
  { id: "l1", phone: "912445118", name: "Chị Hương", date: "23/07/2026", ad: "content a tùng", campaign: "ucmas / tuyển sinh", page: "UCMAS Việt Nam", rank: 2, crm: true, status: "Hợp lệ" },
  { id: "l2", phone: "987002431", name: "Anh Dũng", date: "23/07/2026", ad: "", campaign: "", page: "UCKID Hà Nội", rank: 0, crm: false, status: "Hợp lệ" },
  { id: "l3", phone: "903771260", name: "Chị Mai", date: "22/07/2026", ad: "rèn não bộ", campaign: "ucmas / rèn não", page: "UCMAS Việt Nam", rank: 1, crm: true, status: "Hợp lệ" },
  { id: "l4", phone: "938114907", name: "—", date: "22/07/2026", ad: "quà tặng hè", campaign: "ucmas / quà tặng", page: "UCMAS HCM", rank: 0, crm: false, status: "Trùng" },
  { id: "l5", phone: "977320845", name: "Anh Bình", date: "21/07/2026", ad: "tư duy toán", campaign: "uckid / tư duy", page: "UCKID Hà Nội", rank: 0, crm: false, status: "Hợp lệ" },
  { id: "l6", phone: "120002", name: "—", date: "21/07/2026", ad: "", campaign: "", page: "UCMAS HCM", rank: 0, crm: false, status: "Lỗi" },
  { id: "l7", phone: "965493772", name: "Chị Vân", date: "20/07/2026", ad: "khai giảng", campaign: "uckid / khai giảng", page: "UCKID Đà Nẵng", rank: 3, crm: true, status: "Hợp lệ" },
  { id: "l8", phone: "766000255", name: "Anh Nam", date: "20/07/2026", ad: "content a tùng", campaign: "ucmas / content", page: "UCMAS Việt Nam", rank: 4, crm: true, status: "Hợp lệ" },
];

export const syncSources = [
  { code: "ads_daily", icon: "chart", name: "Quảng cáo", state: "ok", updated: "09:14 hôm nay", rows: 1_240 },
  { code: "leads", icon: "phone", name: "Lead", state: "ok", updated: "09:14 hôm nay", rows: 2_418 },
  { code: "crm_levels", icon: "target", name: "Bậc CRM", state: "warn", updated: "3 ngày trước", rows: 856 },
];

export const syncHistory = [
  { time: "24/07/2026 09:14", source: "Quảng cáo", mode: "Đồng bộ", result: "1.240 dòng · 12 lỗi", duration: "42 giây", errors: 12 },
  { time: "24/07/2026 09:12", source: "Lead", mode: "Đồng bộ", result: "2.418 dòng · 3 lỗi", duration: "1 phút 08", errors: 3 },
  { time: "24/07/2026 09:05", source: "Bậc CRM", mode: "Chạy thử", result: "856 dòng · 0 lỗi", duration: "18 giây", errors: 0 },
  { time: "23/07/2026 18:30", source: "Tất cả", mode: "Đồng bộ", result: "4.514 dòng · 21 lỗi", duration: "2 phút 14", errors: 21 },
];

export const sourceSettings = {
  ads: {
    title: "Nguồn dữ liệu quảng cáo",
    description: "Chi tiêu, tin nhắn và dữ liệu phân phối từ Meta",
    link: "https://docs.google.com/spreadsheets/d/1AdsInsightDemo",
    tab: "Dữ liệu quảng cáo",
    fields: [
      { target: "Mã quảng cáo", required: true, column: "ad_id", transform: "Cắt khoảng", valid: true },
      { target: "Tên chiến dịch", required: true, column: "campaign_name", transform: "Sửa mojibake", valid: true },
      { target: "Ngày", required: true, column: "date_start", transform: "Ngày ISO", valid: true },
      { target: "Chi tiêu", required: true, column: "spend", transform: "Số VN", valid: true },
      { target: "Tin nhắn", required: true, column: "Kết quả", transform: "Số VN", valid: true },
    ],
  },
  leads: {
    title: "Nguồn lead POSCAKE",
    description: "SĐT, thời điểm vào và quảng cáo first-touch",
    link: "https://docs.google.com/spreadsheets/d/1LeadDemo",
    tab: "POSCAKE",
    fields: [
      { target: "Tên khách", required: false, column: "Khách hàng", transform: "Cắt khoảng", valid: true },
      { target: "SĐT", required: true, column: "SĐT phụ huynh", transform: "SĐT VN", valid: true },
      { target: "Ngày vào", required: true, column: "Ngày tạo đơn", transform: "Ngày d/m/y", valid: true },
      { target: "Mã quảng cáo", required: false, column: "ad_id", transform: "Cắt khoảng", valid: true },
    ],
  },
  crm: {
    title: "Nguồn bậc CRM",
    description: "Bậc cao nhất và thông tin tư vấn của từng SĐT",
    link: "https://docs.google.com/spreadsheets/d/1CrmDemo",
    tab: "CRM level",
    fields: [
      { target: "SĐT", required: true, column: "SĐT phụ huynh", transform: "SĐT VN", valid: true },
      { target: "Level UCMAS", required: false, column: "Level UCMAS", transform: "Quy đổi bậc", valid: true },
      { target: "Level UCKID", required: false, column: "Level UCKID", transform: "Quy đổi bậc", valid: true },
      { target: "Trung tâm", required: false, column: "Trung tâm", transform: "Cắt khoảng", valid: true },
    ],
  },
} as const;

export const levelMap = [
  { raw: "L0.R", rank: 0, count: 8 },
  { raw: "L0.K", rank: 0, count: 6 },
  { raw: "L1.KK", rank: 0, count: 5 },
  { raw: "L1", rank: 1, count: 78 },
  { raw: "L2.2A", rank: 2, count: 34 },
  { raw: "L3.1", rank: 3, count: 19 },
  { raw: "L4.3", rank: 4, count: 7 },
  { raw: "L5.NEW", rank: null, count: 3, isNew: true },
];
